# Generated by Django 3.1.1 on 2020-09-26 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoria', models.CharField(max_length=10)),
                ('nombreCategoria', models.CharField(max_length=20)),
                ('listaProductos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.CharField(max_length=10)),
                ('listaProductosTop', models.TextField()),
                ('frecuenciaCompra', models.CharField(max_length=20)),
                ('listaPedidos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rucComercio', models.CharField(max_length=11)),
                ('nombreComercio', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombreUsuario', models.CharField(max_length=20)),
                ('apPaterno', models.CharField(max_length=20)),
                ('apMaterno', models.CharField(max_length=20)),
                ('correoUsuario', models.CharField(max_length=20)),
                ('telefonoUsuario', models.CharField(max_length=20)),
                ('tarjetaBancaria', models.CharField(max_length=20)),
                ('usuarioAcceso', models.CharField(max_length=20)),
                ('contraseñaAcceso', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoRepartidor', models.CharField(max_length=20)),
                ('nombreRepartidor', models.CharField(max_length=20)),
                ('apPaternoRepartidor', models.CharField(max_length=20)),
                ('apMaternoRepartidor', models.CharField(max_length=20)),
                ('correoRepartidor', models.CharField(max_length=20)),
                ('telefonoRepartidor', models.CharField(max_length=20)),
                ('listaPedidos', models.TextField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.CharField(max_length=10)),
                ('nombreProducto', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categoria')),
                ('comercio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.comercio')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroPedido', models.CharField(max_length=10)),
                ('fechaCreacion', models.DateField()),
                ('fechaEntrega', models.DateField()),
                ('costoEnvio', models.FloatField()),
                ('direccionEntrega', models.CharField(max_length=30)),
                ('direccionOrigen', models.CharField(max_length=30)),
                ('estadoPedido', models.CharField(max_length=20)),
                ('precioTotal', models.FloatField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cliente')),
                ('repartidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.repartidor')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usuario'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioUnitario', models.FloatField()),
                ('cantidad', models.IntegerField(default=1)),
                ('precioSubtotal', models.FloatField()),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.producto')),
            ],
        ),
    ]
